spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/db_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    druid:
      aop-patterns: com.spongehah.admin.*  #Spring监控AOP的切入点
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:    # 对上面filters里面的wall的详细配置
          enabled: true
          config:
            drop-table-allow: false   # 禁止删表操作
  
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password: 123456
#    lettuce:
#      pool:
#        max-active: 8  #最大连接
#        max-idle: 8   #最大空闲连接
#        min-idle: 0   #最小空闲连接
#        max-wait: 100ms #连接等待时间
  application:
    name: boot-05-web-admin
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true # 使用ip注册
  profiles:
    active: 

# 配置mybatis规则
#mybatis:
#  # config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  configuration:  # MyBatis全局配置可以写在此处，与config-location配置文件中的配置不能重复设置
#    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_

pagehelper:
  reasonable: true
  
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web: #web模式配置
      exposure:
        include: '*'  #以web方式暴露
  endpoint: # 单独控制暴露某个端点信息 和 详细配置
    health:
      enabled: true 
      show-details: always  # 始终展示详细信息，默认为nerver
    metrics:
      enabled: true
info:
  appName: boot-admin
  version: 2.0.1
  mavenProjectName: @project.artifactId@  #使用@@可以获取maven的pom文件值
  mavenProjectVersion: @project.version@
  
person:
  name: "张三"
  